channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  - tesseract=5.0.1
  - pip=20.1
  - nodejs=16.14.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - robotframework-browser==12.2.0
      - rpaframework==12.10.1 # https://rpaframework.org/releasenotes.html
      #- rpaframework-windows==3.0.0 # https://pypi.org/project/rpaframework-windows/
      - rpaframework-recognition==2.0.0 # https://pypi.org/project/rpaframework-recognition/
rccPostInstall:
  - rfbrowser init